//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Unique.Profile.Communication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unique.Profile.Communication.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso já aprovado.
        /// </summary>
        public static string AccessAlreadyApproved {
            get {
                return ResourceManager.GetString("AccessAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu acesso ainda não foi aprovado.
        /// </summary>
        public static string AccessNotApproved {
            get {
                return ResourceManager.GetString("AccessNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de acesso expirado.
        /// </summary>
        public static string AccessTokenExpired {
            get {
                return ResourceManager.GetString("AccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço não encontrado.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep não encontrado.
        /// </summary>
        public static string AddressZipCodeNotFound {
            get {
                return ResourceManager.GetString("AddressZipCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado.
        /// </summary>
        public static string ApiUnauthorized {
            get {
                return ResourceManager.GetString("ApiUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente já cadastrado.
        /// </summary>
        public static string ClientAlreadyExists {
            get {
                return ResourceManager.GetString("ClientAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não pode ser cadastrado.
        /// </summary>
        public static string ClientCouldNotBeRegistered {
            get {
                return ResourceManager.GetString("ClientCouldNotBeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado.
        /// </summary>
        public static string ClientUnauthorized {
            get {
                return ResourceManager.GetString("ClientUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já validado.
        /// </summary>
        public static string EmailAlreadyValidated {
            get {
                return ResourceManager.GetString("EmailAlreadyValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não validado.
        /// </summary>
        public static string EmailNotValidated {
            get {
                return ResourceManager.GetString("EmailNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso inválido do token informado ao provider.
        /// </summary>
        public static string InvalidAccessTokenProvider {
            get {
                return ResourceManager.GetString("InvalidAccessTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido do provider.
        /// </summary>
        public static string InvalidUserProvider {
            get {
                return ResourceManager.GetString("InvalidUserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Name&apos; deve conter um nome completo.
        /// </summary>
        public static string NameNotComplete {
            get {
                return ResourceManager.GetString("NameNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone já validado.
        /// </summary>
        public static string PhoneAlreadyValidated {
            get {
                return ResourceManager.GetString("PhoneAlreadyValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone não validado.
        /// </summary>
        public static string PhoneNotValidated {
            get {
                return ResourceManager.GetString("PhoneNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de atualização expirado.
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email da conta social não informado.
        /// </summary>
        public static string SocialAccountWithoutEmail {
            get {
                return ResourceManager.GetString("SocialAccountWithoutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone da conta social não informado.
        /// </summary>
        public static string SocialAccountWithoutPhone {
            get {
                return ResourceManager.GetString("SocialAccountWithoutPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já cadastrado.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já cadastrado e foi associado à nova aplicação.
        /// </summary>
        public static string UserAlreadyExistsAndWasAssociatedWithNewApplication {
            get {
                return ResourceManager.GetString("UserAlreadyExistsAndWasAssociatedWithNewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já cadastrado e foi associado à nova aplicação, mas precisa de aprovação de cadastro.
        /// </summary>
        public static string UserAlreadyExistsAndWasAssociatedWithNewApplicationButNeedsApproval {
            get {
                return ResourceManager.GetString("UserAlreadyExistsAndWasAssociatedWithNewApplicationButNeedsApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já está vinculado em outro portal..
        /// </summary>
        public static string UserAlreadyExistsInPortal {
            get {
                return ResourceManager.GetString("UserAlreadyExistsInPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorretos.
        /// </summary>
        public static string UserOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de e-mail incorreto.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de validação de e-mail inválido.
        /// </summary>
        public static string WrongEmailValidationToken {
            get {
                return ResourceManager.GetString("WrongEmailValidationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao menos um dos campos a seguir deve ser preenchido para efetuar o login: E-mail ou UserName.
        /// </summary>
        public static string WrongLoginParameters {
            get {
                return ResourceManager.GetString("WrongLoginParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho incorreto de código de validação de telefone.
        /// </summary>
        public static string WrongPhoneCodeLength {
            get {
                return ResourceManager.GetString("WrongPhoneCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho incorreto de número de telefone.
        /// </summary>
        public static string WrongPhoneNumberLength {
            get {
                return ResourceManager.GetString("WrongPhoneNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de validação de telefone inválido.
        /// </summary>
        public static string WrongPhoneValidationCode {
            get {
                return ResourceManager.GetString("WrongPhoneValidationCode", resourceCulture);
            }
        }
    }
}
